### ISSUE TITLE
第二辆车剩余站会出错

### ISSUE THREAD

**Issue by MrW8848** [a2633063/BusMonitor_Wuhan#2]
第一辆车是对的，但是第二辆车剩余站会算到第三辆车的位置

**Comment by a2633063** [comment]
> 第一辆车是对的，但是第二辆车剩余站会算到第三辆车的位置

看了下似乎并没有此问题 能否提供截图说明下?
是百分百复现吗

**Comment by MrW8848** [comment]
![Screenshot_20201230-162108](https://user-images.githubusercontent.com/49940322/103339019-401e4f00-4abb-11eb-9c49-39ba77078147.png)
![Screenshot_20201230-162056](https://user-images.githubusercontent.com/49940322/103339024-41e81280-4abb-11eb-8e66-75322ca862ec.png)

**Comment by a2633063** [comment]
我没看出你说的`第二辆车剩余站会算到第三辆车的位置`
不过确实在一些情况下无法识别第一辆第二辆车以及默认选择的车站有问题 我先修复这2个问题 给你测试下
另外 改后的ui确实更好看  我也修改成类似效果~

**Comment by MrW8848** [comment]
![Screenshot_20201230-164420](https://user-images.githubusercontent.com/49940322/103340141-524dbc80-4abe-11eb-8067-ab459d949ee6.png)

**Comment by MrW8848** [comment]
![Screenshot_20201230-164417](https://user-images.githubusercontent.com/49940322/103340156-5a0d6100-4abe-11eb-9dc7-e60c9354245d.png)

**Comment by MrW8848** [comment]
![Screenshot_20201230-164417](https://user-images.githubusercontent.com/49940322/103340169-6396c900-4abe-11eb-9a90-2c4c95c3cb4b.png)
![Screenshot_20201230-164420](https://user-images.githubusercontent.com/49940322/103340172-64c7f600-4abe-11eb-8b40-7285bdd67961.png)
看图中709

**Comment by a2633063** [comment]
已更新v1.4.1版本修复此问题
麻烦确认后close此issue

**Comment by a2633063** [comment]
@MrW8848   还在用这个app吗   建立了个qq群 点击链接加入群聊【zBus】：https://jq.qq.com/?_wv=1027&k=6GOE0uXk   加群答案zbus
看是否有兴趣  方便讨论问题

**Comment by MrW8848** [comment]
进群了
