### ISSUE TITLE
建议增加站点是否有地铁站的图标

### ISSUE THREAD

**Issue by MrW8848** [a2633063/BusMonitor_Wuhan#6]

**Comment by a2633063** [comment]
当前api无此功能

**Comment by MrW8848** [comment]
"stopId": "027-I-4395",
"stopName": "高新二路佛祖岭一路", 
"lng": 114.46288558217007,
"lat": 30.47577471173447,
"stopOrder": 1,
"metro": ""
最后这个metro就是

**Comment by a2633063** [comment]
仔细看 所有的metro都是空的

**Comment by MrW8848** [comment]
尝试了一下，确实是个没用的string

**Comment by a2633063** [comment]
目前此metro字段已经有效,后期有时间就把此功能加上

**Comment by a2633063** [comment]
点击链接加入群聊【zBus】：https://jq.qq.com/?_wv=1027&k=6GOE0uXk   加群答案zbus

**Comment by a2633063** [comment]
此功能已经增加,关闭此问题
