### ISSUE TITLE
用不了了

### ISSUE THREAD

**Issue by XOAMOX** [a2633063/BusMonitor_Wuhan#7]
![Screenshot_2021-09-04-09-23-23-067_com zyc busmonitor](https://user-images.githubusercontent.com/48762829/132077979-808a5a82-f71d-40ff-9976-a73f0f1b78f5.jpg)

**Comment by a2633063** [comment]
刚试了下没有问题  可能是网络临时卡一下  多刷新几次试试

**Comment by XOAMOX** [comment]
> 刚试了下没有问题 可能是网络临时卡一下 多刷新几次试试

可以用了关闭问题吧
