### ISSUE TITLE
用不了啦

### ISSUE THREAD

**Issue by pingshu** [a2633063/BusMonitor_Wuhan#8]
用不了啦

**Comment by a2633063** [comment]
测试了下 正常 确认下网络吧

**Comment by pingshu** [comment]
![125E73E3-ABE3-474C-A1D5-A63322DCE71B](https://user-images.githubusercontent.com/22138807/156997013-f292bd62-0f2c-48ad-a328-64c6d28f5c42.jpeg)
![04EB1C55-1D32-447F-B77E-D82994F2BF32](https://user-images.githubusercontent.com/22138807/156997062-2098b21e-4447-4c48-85e8-ae7871d96bf3.jpeg)
空白，没反应

**Comment by pingshu** [comment]
电信4g网

**Comment by a2633063** [comment]
确认了一下   移动4g 5g都正常   电信4g 5g都无法使用  应该是网络问题了

**Comment by pingshu** [comment]
的确，换了联通就可以了
